### ISSUE TITLE
Adding room to zone requires setCoolingThermostatSetpoint

### ISSUE THREAD

**Issue by lroovers** [EggensEng/OTGW-hc3#1]
Hallo Jelle,

Nice start!

 however, one can no longer add the room where this thermostat is located to a zone .. I think defining a dummy setCoolingThermostatSetpoint might suffice.

creating a zone i get ..

[04.08.2022] [22:51:34] [DEBUG] [QUICKAPP298]: onAction: {"deviceId":300,"args":[20.0],"actionName":"setCoolingThermostatSetpoint"}
[04.08.2022] [22:51:34] [WARNING] [QUICKAPP298]: Class does not have setCoolingThermostatSetpoint function defined - action ignored

**Comment by lroovers** [comment]
Adding this function to the tab OtgwDevice suffice indeed

-- handle action for setting set point for Cooling
    -- required to be able to add the room to a zone, although we dont use it within otgw
    -- @author LRoovers
    function OtgwDevice:setCoolingThermostatSetpoint(value) 
        self:updateProperty("setCoolingThermostatSetpoint", value)
    end

**Comment by EggensEng** [comment]
Hi @lroovers 

Thanks a lot for the great input and the testing. I have made a new release referring to this issue.
